# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

path+=/home/$USER/bin
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="spaceship"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(z vi-mode zsh-syntax-highlighting zsh-autosuggestions colored-man-pages docker python pip helm)

PATH=$PATH:/usr/local/sbin

source $ZSH/oh-my-zsh.sh

# want your terminal to support 256 color schemes? I do ...
export TERM="xterm-256color"
#
# # if you do a 'rm *', Zsh will give you a sanity check!
setopt RM_STAR_WAIT
#
# # allows you to type Bash style comments on your command line
# # good 'ol Bash
setopt interactivecomments
#
# # Zsh has a spelling corrector
setopt CORRECT

bindkey 'jk' vi-cmd-mode

export EDITOR="vim"
export VISUAL="vim"
export USE_EDITOR="vim"

# fpath=(/usr/local/share/zsh-completions $fpath)
fpath+=($ZSH/plugins/docker)

autoload -U compinit && compinit

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

for config in "$HOME"/.zshrc.d/* ; do
    source "$config"
done
unset -v config

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZE_DEFAULT_OPS="--extended" # enable us to use regex when matching on results like txt$

export FZF_DEFAULT_COMMAND='ag -g ""'

SPACESHIP_BATTERY_SHOW=false

export PATH="/home/gideon/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
eval "$(direnv hook zsh)"
eval $(thefuck --alias)

source <(kubectl completion zsh | sed s/kubectl/kc/g)
